### ISSUE TITLE
Version info in console may be shown several times

### ISSUE THREAD

**Issue by ildar170975** [nathan-gs/ha-map-card#15]
In a storage mode:
Add one map card on a view - then the version info is shown once:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/c2e2666d-7b8f-480d-be00-30ee02121564)

Open HA Editor - one more message is logged:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/326505d8-ca00-4eb0-b4b3-6764285b812e)

In case of two cards - two messages are logged:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/25e0e997-aa77-4517-948d-f64ecb7c65c2)

---------------------

In yaml mode:

If a view contains 1 card - 2 messages are logged:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/bb1e7431-e2ee-44f6-b80b-25be36053b3f)

If 3 cards - 6 messages:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/517a8b66-09ce-4089-9a59-3f9a2a404999)

-------------

Probably the map-card adds this message to the console on every creation (sorry for a probably wrong term).
Other custom cards (not tested ALL them, honestly) add messages after "loading" (again could use a wrong word).
Check this empty view - the console shows some (not sure about ALL) custom cards:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/42e23621-207d-407e-9402-400b56d00b16)

**Comment by nathan-gs** [comment]
Fixed in v0.5.3

**Comment by ildar170975** [comment]
Still see in 0.5.3:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/b031ed3b-8bec-4027-9fe9-4ee2f7e2e6d1)

**Comment by nathan-gs** [comment]
It already is significantly reduced (HA 2023.11), closing this for now.

**Comment by nathan-gs** [comment]
Fixed in v0.6.0
