### ISSUE TITLE
Now listed in HACS

### ISSUE THREAD

**Issue by systematicallyrandom** [nathan-gs/ha-map-card#97]
This project is now listed in HACS, so the text surrounding installation in the readme can be changed to reflect this.

**Comment by nathan-gs** [comment]
Already fixed in #96, by @tjorim

**Comment by systematicallyrandom** [comment]
I see that now. However in HACS (for me) it's still showing the old version on the readme. I've refreshed the repo in HACS and still the old page. Is there a delay somewhere?

![Screenshot_20241216-070822](https://github.com/user-attachments/assets/06d503fb-07e9-4119-a872-8b061d334b43)

**Comment by nathan-gs** [comment]
A new release will fix that likely, let me do so in the coming days.

**Comment by nathan-gs** [comment]
@systematicallyrandom can you check again, new readme is part of [v1.8.0](https://github.com/nathan-gs/ha-map-card/releases/tag/v1.8.0)

**Comment by systematicallyrandom** [comment]
Yep, looks correct in HACS now! 👍🏻
